export interface MonitorOrg {
  name: string
  sector: 'academia' | 'industry' | 'international' | 'india'
  country: string
  careersUrl?: string
  rssUrl?: string
  apiType: 'rss' | 'usajobs' | 'websearch' | 'adzuna' | 'natureJobs'
  searchQuery: string
  slowFetch?: boolean  // Add extra inter-scan delay to respect org rate limits
}

// ─── Query Design Rules (V2 — 2026-03-23) ────────────────────────────────────
// 1. NO "postdoc" or "postdoctoral" in queries — hard-filtered titles waste Serper calls
// 2. Use site: operator for all orgs with known career portals — eliminates papers/news
// 3. Title terms: "research scientist scientist faculty investigator group leader"
// 4. Negative terms: -postdoctoral where site: isn't used
// ─────────────────────────────────────────────────────────────────────────────

export const MONITOR_ORGS: MonitorOrg[] = [
  // ═══ ACADEMIA — US Government (USAJobs — free, no AI cost) ═══
  { name: "NIH NHLBI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cardiovascular molecular biology NHLBI" },
  { name: "NIH NIGMS", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist molecular biology genomics NIGMS" },
  { name: "NIH NCI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cancer molecular biology NCI" },
  { name: "FDA", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist molecular biology FDA" },
  { name: "CDC", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cardiovascular molecular biology CDC" },

  // ═══ ACADEMIA — RSS feeds (free, no AI cost) ═══
  // RSS URLs fetch live job listings; searchQuery used only if RSS fails → webSearch fallback
  { name: "Cold Spring Harbor Laboratory", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://cshl.edu/careers/feed/",
    searchQuery: "site:cshl.edu/careers research scientist molecular biology genomics cardiovascular" },
  { name: "Nature Jobs", sector: "academia", country: "Global",
    apiType: "rss",
    rssUrl: "https://www.nature.com/naturecareers/rss/latest",
    searchQuery: "research scientist faculty investigator cardiovascular molecular biology genomics" },
  { name: "Science Careers", sector: "academia", country: "Global",
    apiType: "rss",
    rssUrl: "https://jobs.sciencecareers.org/rss/jobs/",
    searchQuery: "research scientist faculty investigator cardiovascular molecular biology" },
  { name: "Jobs.ac.uk", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.jobs.ac.uk/search/?rss=1&keywords=cardiovascular+molecular+biology+research+scientist",
    searchQuery: "research scientist faculty cardiovascular molecular biology UK -postdoctoral" },
  { name: "EuroScienceJobs", sector: "international", country: "Europe",
    apiType: "rss",
    rssUrl: "https://www.eurosciencejobs.com/rss/jobs",
    searchQuery: "research scientist faculty investigator cardiovascular molecular biology Europe" },
  { name: "EMBL Jobs", sector: "international", country: "Germany",
    apiType: "rss",
    rssUrl: "https://www.embl.org/jobs/rss/",
    searchQuery: "EMBL research scientist staff scientist cardiovascular molecular biology genomics" },
  { name: "Wellcome Sanger Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.sanger.ac.uk/careers/rss/",
    searchQuery: "Wellcome Sanger research scientist staff scientist genomics cardiovascular molecular biology" },
  { name: "Francis Crick Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.crick.ac.uk/careers/vacancies/rss",
    searchQuery: "Francis Crick research scientist staff scientist cardiovascular molecular biology" },
  { name: "HigherEdJobs", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://www.higheredjobs.com/rss/jobFeed.cfm?JobCat=203",
    searchQuery: "assistant professor faculty cardiovascular molecular biology US university -postdoctoral" },

  // ═══ ACADEMIA — webSearch (site: operators where career portal is known) ═══
  { name: "Harvard Medical School", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:academicpositions.harvard.edu cardiovascular molecular biology genomics research scientist",
    careersUrl: "https://academicpositions.harvard.edu" },
  { name: "Stanford Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Stanford Medicine research scientist faculty investigator cardiovascular genomics molecular biology 2026 -postdoctoral",
    careersUrl: "https://med.stanford.edu/careers" },
  { name: "Mayo Clinic Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:jobs.mayoclinic.org research scientist cardiovascular molecular biology",
    careersUrl: "https://jobs.mayoclinic.org" },
  { name: "Broad Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:broadinstitute.org/careers research scientist computational biology genomics molecular biology cardiovascular",
    careersUrl: "https://www.broadinstitute.org/careers" },
  { name: "MIT Biology", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "MIT Biology research scientist faculty investigator cardiovascular molecular biology genomics 2026 -postdoctoral" },
  { name: "UCSF", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:jobs.ucsf.edu research scientist cardiovascular molecular biology cell biology",
    careersUrl: "https://jobs.ucsf.edu" },
  { name: "Johns Hopkins Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:jobs.jhu.edu research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://jobs.jhu.edu" },
  { name: "Salk Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:salk.edu/careers research scientist staff scientist cardiovascular cell biology molecular biology",
    careersUrl: "https://www.salk.edu/careers" },
  { name: "Columbia University Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Columbia University Medical Center research scientist faculty cardiovascular molecular biology genomics 2026 -postdoctoral" },
  { name: "Yale School of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Yale School Medicine research scientist faculty cardiovascular genomics molecular biology 2026 -postdoctoral" },
  { name: "Gladstone Institutes", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "site:gladstone.org/careers research scientist staff scientist cardiovascular genomics molecular biology",
    careersUrl: "https://gladstone.org/careers" },
  { name: "Scripps Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Scripps Research scientist investigator cardiovascular molecular biology cell biology 2026 -postdoctoral" },
  { name: "UT Southwestern Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UT Southwestern research scientist faculty investigator cardiovascular molecular biology genomics 2026 -postdoctoral" },
  { name: "Baylor College of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Baylor College Medicine research scientist faculty cardiovascular molecular biology 2026 -postdoctoral" },
  { name: "Washington University St Louis", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Washington University St Louis research scientist faculty cardiovascular molecular biology genomics 2026 -postdoctoral" },
  { name: "Weill Cornell Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Weill Cornell Medicine research scientist faculty cardiovascular molecular biology genomics 2026 -postdoctoral" },

  // ═══ INDUSTRY — USA (site: operators for all known career portals) ═══
  { name: "Genentech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "site:gene.com/careers research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://www.gene.com/careers" },
  { name: "AstraZeneca US", sector: "industry", country: "USA",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:careers.astrazeneca.com research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "Novartis US", sector: "industry", country: "USA",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:novartis.com/careers research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://www.novartis.com/careers" },
  { name: "Pfizer Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "site:pfizer.com/people/careers research scientist cardiovascular cell biology molecular biology",
    careersUrl: "https://www.pfizer.com/people/careers" },
  { name: "Amgen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "site:careers.amgen.com research scientist cardiovascular molecular biology",
    careersUrl: "https://careers.amgen.com" },
  { name: "Bristol Myers Squibb", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Bristol Myers Squibb research scientist cardiovascular genomics molecular biology drug discovery 2026 -postdoctoral" },
  { name: "Regeneron", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "site:careers.regeneron.com research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://careers.regeneron.com" },
  { name: "Moderna", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Moderna research scientist molecular biology cardiovascular mRNA genomics drug discovery 2026 -postdoctoral" },
  { name: "Eli Lilly", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Eli Lilly research scientist cardiovascular molecular biology drug discovery 2026 -postdoctoral" },
  { name: "Merck Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Merck research scientist cardiovascular molecular biology genomics drug discovery 2026 -postdoctoral" },
  { name: "Biogen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Biogen research scientist cardiovascular molecular biology cell biology genomics 2026 -postdoctoral" },
  { name: "Vertex Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Vertex Pharmaceuticals research scientist molecular biology genomics CRISPR drug discovery 2026 -postdoctoral" },
  { name: "Alnylam Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Alnylam Pharmaceuticals research scientist cardiovascular RNA molecular biology therapeutics 2026 -postdoctoral" },
  { name: "10x Genomics", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "10x Genomics research scientist spatial transcriptomics single cell molecular biology 2026 -postdoctoral" },
  { name: "Illumina", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Illumina research scientist genomics molecular biology sequencing 2026 -postdoctoral" },
  { name: "Recursion Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Recursion Pharmaceuticals research scientist cell biology computational biology molecular biology 2026 -postdoctoral" },
  { name: "BioNTech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "BioNTech research scientist mRNA molecular biology cardiovascular genomics 2026 -postdoctoral" },
  { name: "Sanofi Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "site:sanofi.com/en/careers research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://www.sanofi.com/en/careers" },
  { name: "Janssen Research", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Janssen research scientist cardiovascular cell biology molecular biology genomics 2026 -postdoctoral" },
  { name: "Pacific Biosciences", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Pacific Biosciences PacBio research scientist molecular biology genomics sequencing 2026 -postdoctoral" },

  // ═══ INDUSTRY — Europe (UK) ═══
  { name: "AstraZeneca UK", sector: "industry", country: "UK",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:careers.astrazeneca.com research scientist cardiovascular molecular biology Cambridge UK",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "GSK UK", sector: "industry", country: "UK",
    apiType: "websearch",
    searchQuery: "site:gsk.com/en-gb/careers research scientist cardiovascular genomics cell biology molecular biology",
    careersUrl: "https://www.gsk.com/en-gb/careers" },
  { name: "Pfizer UK", sector: "industry", country: "UK",
    apiType: "websearch",
    searchQuery: "site:pfizer.com/people/careers research scientist cardiovascular molecular biology UK Sandwich",
    careersUrl: "https://www.pfizer.com/people/careers" },
  { name: "UCB Pharma UK", sector: "industry", country: "UK",
    apiType: "websearch",
    searchQuery: "site:ucb.com/careers research scientist cardiovascular genomics molecular biology UK",
    careersUrl: "https://www.ucb.com/careers" },

  // ═══ INDUSTRY — Europe (Germany) ═══
  { name: "Bayer Life Sciences", sector: "industry", country: "Germany",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:bayer.com/en/careers research scientist cardiovascular molecular biology cell biology",
    careersUrl: "https://www.bayer.com/en/careers" },
  { name: "Boehringer Ingelheim", sector: "industry", country: "Germany",
    apiType: "websearch",
    searchQuery: "site:boehringer-ingelheim.com/careers research scientist cardiovascular molecular biology cell biology",
    careersUrl: "https://www.boehringer-ingelheim.com/careers" },
  { name: "BioNTech Germany", sector: "industry", country: "Germany",
    apiType: "websearch",
    searchQuery: "site:biontech.de/careers research scientist mRNA molecular biology cardiovascular genomics",
    careersUrl: "https://biontech.de/careers" },
  { name: "Evotec Germany", sector: "industry", country: "Germany",
    apiType: "websearch",
    searchQuery: "site:evotec.com/careers research scientist drug discovery cardiovascular molecular biology",
    careersUrl: "https://www.evotec.com/careers" },
  { name: "MSD Germany", sector: "industry", country: "Germany",
    apiType: "websearch",
    searchQuery: "site:jobs.msd.com research scientist cardiovascular molecular biology Darmstadt",
    careersUrl: "https://jobs.msd.com" },

  // ═══ INDUSTRY — Europe (Switzerland) ═══
  { name: "Novartis Basel", sector: "industry", country: "Switzerland",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:novartis.com/careers research scientist cardiovascular molecular biology genomics Basel",
    careersUrl: "https://www.novartis.com/careers" },
  { name: "Roche Research Basel", sector: "industry", country: "Switzerland",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:roche.com/careers research scientist cardiovascular genomics molecular biology Basel",
    careersUrl: "https://www.roche.com/careers" },

  // ═══ INDUSTRY — Europe (Nordic / Western) ═══
  { name: "Novo Nordisk", sector: "industry", country: "Denmark",
    apiType: "websearch",
    searchQuery: "site:novonordisk.com research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://www.novonordisk.com/careers.html" },
  { name: "Sanofi Paris", sector: "industry", country: "France",
    apiType: "websearch",
    searchQuery: "site:sanofi.com/en/careers research scientist cardiovascular molecular biology Paris",
    careersUrl: "https://www.sanofi.com/en/careers" },
  { name: "AbbVie Ireland", sector: "industry", country: "Ireland",
    apiType: "websearch",
    searchQuery: "site:careers.abbvie.com research scientist molecular biology cardiovascular genomics Dublin Ireland",
    careersUrl: "https://careers.abbvie.com" },
  { name: "UCB Pharma Belgium", sector: "industry", country: "Belgium",
    apiType: "websearch",
    searchQuery: "site:ucb.com/careers research scientist cardiovascular genomics molecular biology Brussels Belgium",
    careersUrl: "https://www.ucb.com/careers" },
  { name: "Astellas Europe", sector: "industry", country: "Netherlands",
    apiType: "websearch",
    searchQuery: "site:astellas.com/en/careers research scientist molecular biology cardiovascular Leiden Netherlands",
    careersUrl: "https://www.astellas.com/en/careers" },

  // ═══ INDUSTRY — Asia (Japan) — deduplicated to 4 canonical entries ═══
  { name: "Takeda Japan", sector: "industry", country: "Japan",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:takeda.com/en-us/careers research scientist cardiovascular molecular biology Tokyo",
    careersUrl: "https://www.takeda.com/en-us/careers" },
  { name: "Daiichi Sankyo Japan", sector: "industry", country: "Japan",
    apiType: "websearch",
    searchQuery: "site:daiichisankyo.com/careers research scientist cardiovascular molecular biology Tokyo",
    careersUrl: "https://www.daiichisankyo.com/careers" },
  { name: "Astellas Japan", sector: "industry", country: "Japan",
    apiType: "websearch",
    searchQuery: "site:astellas.com/en/careers research scientist molecular biology cardiovascular Tokyo Japan",
    careersUrl: "https://www.astellas.com/en/careers" },
  { name: "Eisai Japan", sector: "industry", country: "Japan",
    apiType: "websearch",
    searchQuery: "site:eisai.com/global/careers research scientist molecular biology cardiovascular neuroscience Tokyo",
    careersUrl: "https://www.eisai.com/global/careers" },
  { name: "Ono Pharmaceutical", sector: "industry",
    country: "Japan", apiType: "websearch",
    searchQuery: "Ono Pharmaceutical research scientist molecular biology immunology cardiovascular 2026 -postdoctoral" },
  { name: "Chugai Pharmaceutical", sector: "industry",
    country: "Japan", apiType: "websearch",
    searchQuery: "Chugai Pharmaceutical research scientist molecular biology cardiovascular genomics 2026 -postdoctoral" },
  { name: "Mitsubishi Tanabe Pharma", sector: "industry",
    country: "Japan", apiType: "websearch",
    searchQuery: "Mitsubishi Tanabe Pharma research scientist cardiovascular molecular biology 2026 -postdoctoral" },

  // ═══ INDUSTRY — Asia (Singapore) ═══
  { name: "Novartis Singapore", sector: "industry", country: "Singapore",
    apiType: "websearch",
    searchQuery: "site:novartis.com/careers research scientist cardiovascular molecular biology genomics Singapore",
    careersUrl: "https://www.novartis.com/careers" },
  { name: "GSK Singapore", sector: "industry", country: "Singapore",
    apiType: "websearch",
    searchQuery: "site:gsk.com/en-gb/careers research scientist molecular biology cardiovascular genomics Singapore",
    careersUrl: "https://www.gsk.com/en-gb/careers" },
  { name: "Takeda Singapore", sector: "industry", country: "Singapore",
    apiType: "websearch",
    searchQuery: "site:takeda.com/en-us/careers research scientist cardiovascular molecular biology Singapore",
    careersUrl: "https://www.takeda.com/en-us/careers" },
  { name: "A*STAR Singapore", sector: "industry",
    country: "Singapore", apiType: "websearch",
    searchQuery: "site:a-star.edu.sg/careers research scientist cardiovascular molecular biology genomics Singapore",
    careersUrl: "https://www.a-star.edu.sg/careers" },
  { name: "Roche Singapore", sector: "industry",
    country: "Singapore", apiType: "websearch",
    searchQuery: "site:roche.com/careers research scientist molecular biology cardiovascular genomics Singapore",
    careersUrl: "https://www.roche.com/careers" },
  { name: "AbbVie Singapore", sector: "industry",
    country: "Singapore", apiType: "websearch",
    searchQuery: "site:careers.abbvie.com research scientist molecular biology immunology cardiovascular Singapore",
    careersUrl: "https://careers.abbvie.com" },
  { name: "Bayer Asia", sector: "industry",
    country: "Singapore", apiType: "websearch",
    searchQuery: "site:bayer.com/en/careers research scientist cardiovascular molecular biology cell biology Singapore",
    careersUrl: "https://www.bayer.com/en/careers" },

  // ═══ INDUSTRY — Asia (South Korea) ═══
  { name: "Samsung Biologics", sector: "industry", country: "South Korea",
    apiType: "websearch",
    searchQuery: "site:samsungbiologics.com/careers research scientist molecular biology genomics Incheon",
    careersUrl: "https://www.samsungbiologics.com/careers" },
  { name: "Celltrion", sector: "industry", country: "South Korea",
    apiType: "websearch",
    searchQuery: "site:celltrion.com/en-us/careers research scientist molecular biology cardiovascular Incheon",
    careersUrl: "https://www.celltrion.com/en-us/careers" },
  { name: "Yuhan Corporation", sector: "industry",
    country: "South Korea", apiType: "websearch",
    searchQuery: "Yuhan Corporation research scientist cardiovascular molecular biology genomics Seoul 2026 -postdoctoral" },

  // ═══ INDUSTRY — Asia (China) ═══
  { name: "AstraZeneca China", sector: "industry", country: "China",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:careers.astrazeneca.com research scientist cardiovascular molecular biology Shanghai China",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "Roche China", sector: "industry", country: "China",
    apiType: "websearch",
    searchQuery: "site:roche.com/careers research scientist cardiovascular molecular biology genomics Shanghai",
    careersUrl: "https://www.roche.com/careers" },
  { name: "BeiGene Research", sector: "industry",
    country: "China", apiType: "websearch",
    searchQuery: "BeiGene research scientist molecular biology cardiovascular oncology genomics Beijing Shanghai 2026 -postdoctoral" },
  { name: "Zymeworks China", sector: "industry",
    country: "China", apiType: "websearch",
    searchQuery: "Zymeworks research scientist molecular biology cardiovascular antibody 2026 -postdoctoral" },

  // ═══ INDUSTRY — Australia ═══
  { name: "CSL Behring", sector: "industry",
    country: "Australia", apiType: "websearch",
    searchQuery: "CSL Behring research scientist molecular biology cardiovascular genomics Melbourne 2026 -postdoctoral" },
  { name: "Pfizer Australia", sector: "industry",
    country: "Australia", apiType: "websearch",
    searchQuery: "Pfizer Australia research scientist cardiovascular molecular biology 2026 -postdoctoral" },

  // ═══ INTERNATIONAL — Research Labs ═══
  { name: "MRC LMS London", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC London Institute Medical Sciences research scientist cardiovascular molecular biology 2026 -postdoctoral" },
  { name: "Max Planck Heart and Lung", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Max Planck Institute Heart Lung research scientist cardiovascular molecular biology genomics 2026 -postdoctoral" },
  { name: "Karolinska Institute", sector: "international", country: "Sweden",
    apiType: "websearch",
    searchQuery: "site:ki.se/en/vacancies research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://ki.se/en/vacancies" },
  { name: "ETH Zurich", sector: "international", country: "Switzerland",
    apiType: "websearch",
    searchQuery: "site:jobs.ethz.ch research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://jobs.ethz.ch" },
  { name: "University of Toronto", sector: "international", country: "Canada",
    apiType: "websearch",
    searchQuery: "University of Toronto research scientist faculty investigator cardiovascular molecular biology genomics 2026 -postdoctoral" },
  { name: "Peter MacCallum Cancer Centre", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "Peter MacCallum Cancer Centre research scientist molecular biology genomics 2026 -postdoctoral" },

  // ═══ INDIA — Academic Institutes ═══
  { name: "NCBS Bangalore", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:ncbs.res.in/jobs research scientist faculty cardiovascular molecular biology",
    careersUrl: "https://www.ncbs.res.in/jobs" },
  { name: "TIFR Mumbai", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "TIFR Mumbai research scientist faculty biology cardiovascular molecular biology 2026 -postdoctoral" },
  { name: "IISc Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IISc Bangalore research scientist faculty molecular biology cardiovascular genomics 2026 -postdoctoral" },
  { name: "IGIB Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IGIB Delhi faculty research scientist genomics molecular biology cardiovascular 2026 -postdoctoral" },
  { name: "CCMB Hyderabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "CCMB Hyderabad faculty research scientist molecular biology cell biology 2026 -postdoctoral" },
  { name: "inStem Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "inStem Bangalore research scientist faculty cardiovascular stem cell biology molecular biology 2026 -postdoctoral" },
  { name: "NII Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "NII Delhi faculty research scientist molecular biology immunology cardiovascular 2026 -postdoctoral" },
  { name: "JNCASR Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "JNCASR Bangalore research scientist faculty molecular biology genomics cardiovascular 2026 -postdoctoral" },
  { name: "IISER Pune", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Pune faculty assistant professor biology cardiovascular molecular biology 2026" },
  { name: "RCB Faridabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "RCB Faridabad faculty research scientist molecular biology cardiovascular 2026 -postdoctoral" },
  { name: "DBT-THSTI Faridabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "THSTI Faridabad faculty research scientist cardiovascular translational molecular biology 2026 -postdoctoral" },
  { name: "RGCB Trivandrum", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "RGCB Trivandrum faculty research scientist molecular biology cardiovascular genomics 2026 -postdoctoral" },

  // ═══ INDIA — Pharma / Biotech ═══
  { name: "Biocon Biologics", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "site:biocon.com/careers research scientist molecular biology cardiovascular genomics",
    careersUrl: "https://www.biocon.com/careers" },
  { name: "Syngene International", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "Syngene International research scientist molecular biology cardiovascular drug discovery 2026 -postdoctoral" },
  { name: "AstraZeneca India", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:careers.astrazeneca.com research scientist cardiovascular molecular biology India" },
  { name: "Dr Reddy's Laboratories", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Dr Reddy research scientist molecular biology cardiovascular 2026 -postdoctoral" },
  { name: "Sun Pharmaceutical", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Sun Pharma research scientist molecular biology cardiovascular 2026 -postdoctoral" },
  { name: "Cipla Research", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Cipla research scientist molecular biology respiratory cardiovascular 2026 -postdoctoral" },
  { name: "Piramal Pharma", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Piramal Pharma research scientist molecular biology cardiovascular cell biology 2026 -postdoctoral" },
  { name: "Jubilant Biosys", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Jubilant Biosys research scientist molecular biology cardiovascular drug discovery 2026 -postdoctoral" },
  { name: "Aragen Bioscience", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Aragen Bioscience research scientist molecular biology cardiovascular CRO 2026 -postdoctoral" },
  { name: "Anthem Biosciences", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Anthem Biosciences research scientist molecular biology cardiovascular 2026 -postdoctoral" },
  { name: "Tata Memorial Centre", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Tata Memorial Centre research scientist molecular biology cancer cardiovascular 2026 -postdoctoral" },
  { name: "Serum Institute India", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Serum Institute India research scientist molecular biology immunology 2026 -postdoctoral" },
  { name: "Lupin Research", sector: "india",
    country: "India", apiType: "websearch",
    searchQuery: "Lupin research scientist molecular biology cardiovascular drug discovery 2026 -postdoctoral" },

  // ═══ INDIA — Tier 1 IITs ═══
  { name: "IIT Bombay Biosciences", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Bombay assistant professor faculty biosciences molecular biology cardiovascular genomics 2026" },
  { name: "IIT Delhi Biochemical Engineering", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IIT Delhi assistant professor faculty biochemistry molecular biology genomics 2026" },

  // ═══ INDIA — IISERs ═══
  { name: "IISER Kolkata", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Kolkata faculty assistant professor cardiovascular molecular biology genomics 2026" },
  { name: "IISER Bhopal", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Bhopal faculty assistant professor biology genomics molecular biology 2026" },
  { name: "IISER Mohali", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Mohali faculty assistant professor molecular biology cardiovascular 2026" },
  { name: "IISER Thiruvananthapuram", sector: "india", country: "India",
    apiType: "websearch", slowFetch: true,
    searchQuery: "IISER Thiruvananthapuram faculty assistant professor molecular biology cardiovascular genomics 2026" },

  // ═══ GLOBAL PHARMA — International sector ═══
  { name: "Roche", sector: "international", country: "Switzerland",
    apiType: "websearch", slowFetch: true,
    searchQuery: "site:roche.com/careers research scientist investigator cardiovascular genomics molecular biology",
    careersUrl: "https://www.roche.com/careers" },
  { name: "GlaxoSmithKline GSK", sector: "industry", country: "UK",
    apiType: "websearch",
    searchQuery: "site:gsk.com/en-gb/careers research scientist cardiovascular molecular biology genomics",
    careersUrl: "https://www.gsk.com/en-gb/careers/" },

  // ═══ INTERNATIONAL — Additional Research Labs ═══
  { name: "WEHI Melbourne", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "site:wehi.edu.au/careers research scientist cardiovascular genomics molecular biology",
    careersUrl: "https://www.wehi.edu.au/careers" },
  { name: "MRC Harwell", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC Harwell Institute research scientist cardiovascular genomics molecular biology 2026 -postdoctoral" },

  // ═══ FREE SOURCES — Indeed RSS (zero cost, direct confirmed job listings) ═══
  { name: "Indeed RSS - Research Scientist Cardiovascular US",
    sector: "industry", country: "USA",
    apiType: "rss",
    rssUrl: "https://www.indeed.com/rss?q=research+scientist+cardiovascular+molecular+biology&l=United+States&sort=date&fromage=14",
    searchQuery: "research scientist cardiovascular molecular biology" },

  { name: "Indeed RSS - Assistant Professor Biology US",
    sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://www.indeed.com/rss?q=assistant+professor+molecular+biology+cardiovascular&l=United+States&sort=date&fromage=21",
    searchQuery: "assistant professor molecular biology cardiovascular" },

  { name: "Indeed RSS - Scientist Molecular Biology India",
    sector: "india", country: "India",
    apiType: "rss",
    rssUrl: "https://www.indeed.co.in/rss?q=research+scientist+molecular+biology+cardiovascular&l=India&sort=date&fromage=14",
    searchQuery: "research scientist molecular biology India" },
]

// Total: 81 orgs — deduplicated (removed: Takeda Pharmaceuticals Japan, Daiichi Sankyo, Astellas Pharma, Eisai Research)
// V2 enhancements: site: operators, no postdoc in queries, -postdoctoral exclusions
// Deploy Trigger: 2026-03-23
