export interface MonitorOrg {
  name: string
  sector: 'academia' | 'industry' | 'international' | 'india'
  country: string
  careersUrl?: string
  rssUrl?: string
  apiType: 'rss' | 'usajobs' | 'websearch' | 'adzuna' | 'natureJobs'
  searchQuery: string
}

// ─── webSearch is ONLY used for orgs with no free source ─────────────────────
// Max 15 websearch orgs. All others use RSS or USAJobs (free, no AI cost).
// Cost: ~60 webSearch calls/month @ ~$0.03/call = ~$1-2/month for monitor

export const MONITOR_ORGS: MonitorOrg[] = [
  // ═══ ACADEMIA — US Government (USAJobs — free, no AI cost) ═══
  { name: "NIH NHLBI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "cardiovascular postdoc researcher NHLBI" },
  { name: "NIH NIGMS", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "postdoctoral researcher molecular biology NIGMS" },
  { name: "NIH NCI", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cancer biology NCI" },
  { name: "FDA", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist molecular biology FDA" },
  { name: "CDC", sector: "academia", country: "USA",
    apiType: "usajobs",
    searchQuery: "research scientist cardiovascular molecular biology CDC" },

  // ═══ ACADEMIA — RSS feeds (free, no AI cost) ═══
  { name: "Cold Spring Harbor Laboratory", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://cshl.edu/careers/feed/",
    searchQuery: "Cold Spring Harbor postdoc molecular biology genomics" },
  { name: "Nature Jobs", sector: "academia", country: "Global",
    apiType: "rss",
    rssUrl: "https://www.nature.com/naturecareers/rss/latest",
    searchQuery: "postdoc cardiovascular molecular biology nature jobs" },
  { name: "Science Careers", sector: "academia", country: "Global",
    apiType: "rss",
    rssUrl: "https://jobs.sciencecareers.org/rss/jobs/",
    searchQuery: "postdoc cardiovascular molecular biology science careers" },
  { name: "Jobs.ac.uk", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.jobs.ac.uk/search/?rss=1&keywords=cardiovascular+postdoc+molecular+biology",
    searchQuery: "cardiovascular postdoc molecular biology UK" },
  { name: "EuroScienceJobs", sector: "international", country: "Europe",
    apiType: "rss",
    rssUrl: "https://www.eurosciencejobs.com/rss/jobs",
    searchQuery: "postdoc cardiovascular molecular biology Europe" },
  { name: "EMBL Jobs", sector: "international", country: "Germany",
    apiType: "rss",
    rssUrl: "https://www.embl.org/jobs/rss/",
    searchQuery: "EMBL postdoctoral fellowship cardiovascular molecular biology" },
  { name: "Wellcome Sanger Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.sanger.ac.uk/careers/rss/",
    searchQuery: "Wellcome Sanger postdoctoral researcher genomics cardiovascular" },
  { name: "Francis Crick Institute", sector: "international", country: "UK",
    apiType: "rss",
    rssUrl: "https://www.crick.ac.uk/careers/vacancies/rss",
    searchQuery: "Francis Crick postdoc cardiovascular molecular biology" },
  { name: "HigherEdJobs", sector: "academia", country: "USA",
    apiType: "rss",
    rssUrl: "https://www.higheredjobs.com/rss/jobFeed.cfm?JobCat=203",
    searchQuery: "postdoc cardiovascular molecular biology US university" },

  // ═══ ACADEMIA — webSearch (no free source — keep to 15 total) ═══
  { name: "Harvard Medical School", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Harvard Medical School postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://academicpositions.harvard.edu" },
  { name: "Stanford Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Stanford Medicine postdoctoral researcher cardiovascular 2026",
    careersUrl: "https://med.stanford.edu/careers" },
  { name: "Mayo Clinic Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Mayo Clinic postdoc research scientist cardiovascular 2026",
    careersUrl: "https://jobs.mayoclinic.org" },
  { name: "Broad Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Broad Institute postdoctoral associate genomics molecular biology 2026",
    careersUrl: "https://www.broadinstitute.org/careers" },
  { name: "MIT Biology", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "MIT postdoctoral researcher molecular biology cardiovascular 2026" },
  { name: "UCSF", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UCSF postdoc cardiovascular cell biology molecular biology 2026",
    careersUrl: "https://jobs.ucsf.edu" },
  { name: "Johns Hopkins Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Johns Hopkins postdoctoral researcher cardiovascular 2026",
    careersUrl: "https://jobs.jhu.edu" },
  { name: "Salk Institute", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Salk Institute postdoc cardiovascular cell biology 2026",
    careersUrl: "https://www.salk.edu/careers" },
  { name: "Columbia University Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Columbia University postdoc cardiovascular research 2026" },
  { name: "Yale School of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Yale Medicine postdoctoral researcher cardiovascular 2026" },
  { name: "Gladstone Institutes", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Gladstone Institutes postdoc cardiovascular genomics 2026",
    careersUrl: "https://gladstone.org/careers" },
  { name: "Scripps Research", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Scripps Research postdoctoral scientist cardiovascular 2026" },
  { name: "UT Southwestern Medical Center", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "UT Southwestern postdoc cardiovascular research 2026" },
  { name: "Baylor College of Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Baylor College Medicine postdoc cardiovascular 2026" },
  { name: "Washington University St Louis", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "WashU postdoctoral researcher cardiovascular molecular biology 2026" },
  { name: "Weill Cornell Medicine", sector: "academia", country: "USA",
    apiType: "websearch",
    searchQuery: "Weill Cornell postdoc cardiovascular research scientist 2026" },

  // ═══ INDUSTRY — webSearch (8 highest-probability orgs kept) ═══
  // Removed: Novartis US, Pfizer Research, BMS, Eli Lilly, Merck Research, Biogen,
  //          Vertex, Alnylam, Illumina, BioNTech, Sanofi Research, Janssen Research
  // These have JS-rendered career pages, auth walls, or are poorly indexed for websearch.
  { name: "Genentech", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Genentech research scientist cardiovascular molecular biology 2026",
    careersUrl: "https://www.gene.com/careers" },
  { name: "AstraZeneca US", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "AstraZeneca research scientist cardiovascular postdoc 2026",
    careersUrl: "https://careers.astrazeneca.com" },
  { name: "Amgen", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Amgen research scientist cardiovascular molecular biology 2026",
    careersUrl: "https://careers.amgen.com" },
  { name: "Regeneron", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Regeneron scientist cardiovascular molecular biology 2026",
    careersUrl: "https://careers.regeneron.com" },
  { name: "10x Genomics", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "10x Genomics scientist spatial transcriptomics molecular biology 2026" },
  { name: "Recursion Pharmaceuticals", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Recursion scientist cell biology computational biology 2026" },
  { name: "Pacific Biosciences", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "PacBio scientist molecular biology genomics sequencing 2026" },
  { name: "Moderna", sector: "industry", country: "USA",
    apiType: "websearch",
    searchQuery: "Moderna research scientist molecular biology cardiovascular 2026" },

  // ═══ INTERNATIONAL — RSS feeds (free, no AI cost) ═══
  { name: "MRC LMS London", sector: "international", country: "UK",
    apiType: "websearch",
    searchQuery: "MRC London Institute Medical Sciences postdoc cardiovascular 2026" },
  { name: "Max Planck Heart and Lung", sector: "international", country: "Germany",
    apiType: "websearch",
    searchQuery: "Max Planck Institute Heart Lung postdoc cardiovascular 2026" },
  { name: "Karolinska Institute", sector: "international", country: "Sweden",
    apiType: "websearch",
    searchQuery: "Karolinska Institute postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://ki.se/en/vacancies" },
  { name: "ETH Zurich", sector: "international", country: "Switzerland",
    apiType: "websearch",
    searchQuery: "ETH Zurich postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://jobs.ethz.ch" },
  { name: "University of Toronto", sector: "international", country: "Canada",
    apiType: "websearch",
    searchQuery: "University of Toronto postdoc cardiovascular molecular biology 2026" },
  { name: "A*STAR Singapore", sector: "international", country: "Singapore",
    apiType: "websearch",
    searchQuery: "ASTAR Singapore postdoc cardiovascular molecular biology 2026",
    careersUrl: "https://www.a-star.edu.sg/careers" },
  { name: "Peter MacCallum Cancer Centre", sector: "international", country: "Australia",
    apiType: "websearch",
    searchQuery: "Peter MacCallum postdoc molecular biology genomics 2026" },

  // ═══ INDIA — webSearch (6 most active, best-indexed institutes) ═══
  // Removed: NII Delhi, JNCASR Bangalore, IISER Pune, RCB Faridabad,
  //          DBT-THSTI Faridabad, RGCB Trivandrum, Biocon Biologics,
  //          Syngene International, AstraZeneca India
  // site: operators added to all queries to constrain AI search to official careers pages first.
  { name: "NCBS Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "NCBS Bangalore postdoctoral fellow research scientist opening 2026 site:ncbs.res.in OR site:academicjobsonline.org",
    careersUrl: "https://www.ncbs.res.in/jobs" },
  { name: "IISc Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IISc Bangalore postdoc research associate molecular biology 2026 site:iisc.ac.in OR site:indiabioscience.org" },
  { name: "TIFR Mumbai", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "TIFR Mumbai postdoc biology opening 2026 site:tifr.res.in OR site:indiabioscience.org" },
  { name: "inStem Bangalore", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "inStem Bangalore postdoctoral cardiovascular stem cell 2026 site:instem.res.in" },
  { name: "CCMB Hyderabad", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "CCMB Hyderabad postdoc molecular biology 2026 site:ccmb.res.in OR site:indiabioscience.org" },
  { name: "IGIB Delhi", sector: "india", country: "India",
    apiType: "websearch",
    searchQuery: "IGIB Delhi postdoc genomics molecular biology 2026 site:igib.res.in" },

  // ═══ INDIA — RSS feeds (free, aggregates NCBS/inStem/CCMB/IGIB/ICMR/DBT/CSIR) ═══
  { name: "IndiaBioscience Jobs", sector: "india", country: "India",
    apiType: "rss",
    rssUrl: "https://indiabioscience.org/jobs/rss",
    searchQuery: "India bioscience postdoc research scientist cardiovascular molecular biology" },
  { name: "Employment News Research", sector: "india", country: "India",
    apiType: "rss",
    rssUrl: "https://www.employmentnews.gov.in/feed",
    searchQuery: "ICMR DRDO DST research scientist postdoc India government" },
]
